/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.GridLayout;
import javax.swing.JButton;



/**
 *
 * @author Mayro
 */
public class Desktop extends javax.swing.JFrame {

    /**
     * Creates new form Desktop
     */
    public Desktop() {
        initComponents();
        this.trocaPaineis(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaQuick = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaSelection = new javax.swing.JTable();
        PainelSobreposto = new javax.swing.JPanel();
        botaoImportar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botaoGerar = new javax.swing.JButton();
        painelGeracaoNumeros = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoQuantidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoImplementar = new javax.swing.JButton();
        botaoGerarNumeros = new javax.swing.JButton();
        botaoFecharGeracao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botaoMedias = new javax.swing.JButton();
        botaoExportarOrdenacao = new javax.swing.JButton();
        botaoGerarGrafico = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 750));
        setPreferredSize(new java.awt.Dimension(600, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaQuick.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Itens", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaQuick);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 270, 400));

        tabelaSelection.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Itens", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaSelection);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 270, 400));

        PainelSobreposto.setBackground(new java.awt.Color(0, 153, 153));
        PainelSobreposto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoImportar.setBackground(new java.awt.Color(255, 204, 51));
        botaoImportar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoImportar.setForeground(new java.awt.Color(51, 51, 51));
        botaoImportar.setText("Importar Números");
        botaoImportar.setBorder(null);
        PainelSobreposto.add(botaoImportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 56, 130, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MÉTODOS DE  ORDENAÇÃO");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PainelSobreposto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        botaoGerar.setBackground(new java.awt.Color(102, 255, 204));
        botaoGerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoGerar.setForeground(new java.awt.Color(51, 51, 51));
        botaoGerar.setText("Gerar Números");
        botaoGerar.setBorder(null);
        botaoGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarActionPerformed(evt);
            }
        });
        PainelSobreposto.add(botaoGerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 40));

        jPanel1.add(PainelSobreposto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 100));

        painelGeracaoNumeros.setBackground(new java.awt.Color(0, 102, 102));
        painelGeracaoNumeros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GERAÇÃO DE NÚMEROS ALEATÓRIOS");
        painelGeracaoNumeros.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, -1, -1));

        campoQuantidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        painelGeracaoNumeros.add(campoQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("K");
        painelGeracaoNumeros.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 50, 20, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantidade");
        painelGeracaoNumeros.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        botaoImplementar.setBackground(new java.awt.Color(255, 204, 51));
        botaoImplementar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoImplementar.setForeground(new java.awt.Color(51, 51, 51));
        botaoImplementar.setText("Implementar Métodos");
        botaoImplementar.setBorder(null);
        painelGeracaoNumeros.add(botaoImplementar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 160, 30));

        botaoGerarNumeros.setBackground(new java.awt.Color(102, 255, 204));
        botaoGerarNumeros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoGerarNumeros.setForeground(new java.awt.Color(51, 51, 51));
        botaoGerarNumeros.setText("Gerar Números");
        botaoGerarNumeros.setBorder(null);
        painelGeracaoNumeros.add(botaoGerarNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 130, 30));

        botaoFecharGeracao.setBackground(new java.awt.Color(255, 51, 51));
        botaoFecharGeracao.setForeground(new java.awt.Color(51, 51, 51));
        botaoFecharGeracao.setText("X");
        botaoFecharGeracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharGeracaoActionPerformed(evt);
            }
        });
        painelGeracaoNumeros.add(botaoFecharGeracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, -1));

        jPanel1.add(painelGeracaoNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 100));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quick Sort");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Selection Sort");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        botaoMedias.setBackground(new java.awt.Color(102, 102, 255));
        botaoMedias.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        botaoMedias.setForeground(new java.awt.Color(255, 255, 255));
        botaoMedias.setText("Médias Anteriores");
        botaoMedias.setBorder(null);
        jPanel1.add(botaoMedias, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 660, 120, 30));

        botaoExportarOrdenacao.setBackground(new java.awt.Color(255, 204, 51));
        botaoExportarOrdenacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoExportarOrdenacao.setForeground(new java.awt.Color(51, 51, 51));
        botaoExportarOrdenacao.setText("Exportar Ordenação");
        botaoExportarOrdenacao.setBorder(null);
        jPanel1.add(botaoExportarOrdenacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 130, 40));

        botaoGerarGrafico.setBackground(new java.awt.Color(255, 204, 51));
        botaoGerarGrafico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoGerarGrafico.setForeground(new java.awt.Color(51, 51, 51));
        botaoGerarGrafico.setText("Gerar Gráficos");
        botaoGerarGrafico.setBorder(null);
        jPanel1.add(botaoGerarGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 130, 40));

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Quick");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, -1, -1));

        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Selection");
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharGeracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharGeracaoActionPerformed
        trocaPaineis(false);
    }//GEN-LAST:event_botaoFecharGeracaoActionPerformed

    private void botaoGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarActionPerformed
        trocaPaineis(true);
    }//GEN-LAST:event_botaoGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelSobreposto;
    private javax.swing.JButton botaoExportarOrdenacao;
    private javax.swing.JButton botaoFecharGeracao;
    private javax.swing.JButton botaoGerar;
    private javax.swing.JButton botaoGerarGrafico;
    private javax.swing.JButton botaoGerarNumeros;
    private javax.swing.JButton botaoImplementar;
    private javax.swing.JButton botaoImportar;
    private javax.swing.JButton botaoMedias;
    private javax.swing.JTextField campoQuantidade;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel painelGeracaoNumeros;
    private javax.swing.JTable tabelaQuick;
    private javax.swing.JTable tabelaSelection;
    // End of variables declaration//GEN-END:variables
    
    private void trocaPaineis(boolean gerarNumeros){
        painelGeracaoNumeros.setVisible(gerarNumeros);
        PainelSobreposto.setVisible(!gerarNumeros);
    }

}
