/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Paineis.GraficosController;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 55989
 */
public class Grafico extends javax.swing.JDialog {
    private final GraficosController controller;
    /**
     * Creates new form Gráfico
     */
    public Grafico(Desktop desktop, boolean modal, DefaultTableModel selection, DefaultTableModel quick) {
        super(desktop, modal);
        initComponents();
        controller = new GraficosController(desktop, this, selection, quick);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botaoExportarGraficoQuick = new javax.swing.JButton();
        botaoExportarGraficoSelection = new javax.swing.JButton();
        painelSelection = new javax.swing.JDesktopPane();
        painelQuick = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Gráficos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 70, 69));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 170, 40));

        botaoExportarGraficoQuick.setBackground(new java.awt.Color(46, 212, 123));
        botaoExportarGraficoQuick.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        botaoExportarGraficoQuick.setForeground(new java.awt.Color(102, 102, 102));
        botaoExportarGraficoQuick.setText("Exportar Gráfico");
        botaoExportarGraficoQuick.setBorder(null);
        botaoExportarGraficoQuick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExportarGraficoQuickActionPerformed(evt);
            }
        });
        jPanel1.add(botaoExportarGraficoQuick, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 180, 40));

        botaoExportarGraficoSelection.setBackground(new java.awt.Color(46, 212, 123));
        botaoExportarGraficoSelection.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        botaoExportarGraficoSelection.setForeground(new java.awt.Color(102, 102, 102));
        botaoExportarGraficoSelection.setText("Exportar Gráfico");
        botaoExportarGraficoSelection.setBorder(null);
        botaoExportarGraficoSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExportarGraficoSelectionActionPerformed(evt);
            }
        });
        jPanel1.add(botaoExportarGraficoSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 180, 40));
        jPanel1.add(painelSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 280, 290));
        jPanel1.add(painelQuick, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 280, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.fechar();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoExportarGraficoQuickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExportarGraficoQuickActionPerformed
        controller.exportarGraficos(2);
    }//GEN-LAST:event_botaoExportarGraficoQuickActionPerformed

    private void botaoExportarGraficoSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExportarGraficoSelectionActionPerformed
       controller.exportarGraficos(1);
    }//GEN-LAST:event_botaoExportarGraficoSelectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Grafico dialog = new Grafico(new Desktop(), true, new DefaultTableModel(), new DefaultTableModel());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExportarGraficoQuick;
    private javax.swing.JButton botaoExportarGraficoSelection;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane painelQuick;
    private javax.swing.JDesktopPane painelSelection;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getPainelQuick() {
        return painelQuick;
    }

    public JDesktopPane getPainelSelection() {
        return painelSelection;
    }

    
}
